# Generated by Django 4.1.3 on 2022-11-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_subscribe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='paid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscribe_plan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
