# Generated by Django 4.1.3 on 2022-11-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0004_alter_amenity_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studioimage',
            name='image',
            field=models.ImageField(upload_to='PB/images/studios/'),
        ),
    ]
