# Generated by Django 4.1.3 on 2022-11-11 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0008_alter_amenity_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='studio',
        ),
        migrations.AddField(
            model_name='amenity',
            name='studio',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='studios.studio'),
            preserve_default=False,
        ),
    ]
