# Generated by Django 4.1.3 on 2022-11-11 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0009_remove_amenity_studio_amenity_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='studios.studio'),
        ),
    ]
