# Generated by Django 4.1.3 on 2022-11-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0010_alter_amenity_studio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='location',
        ),
        migrations.AddField(
            model_name='studio',
            name='lat',
            field=models.FloatField(default=1, verbose_name='Latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studio',
            name='lon',
            field=models.FloatField(default=1, verbose_name='Longitude'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studio',
            name='postal_code',
            field=models.CharField(max_length=7),
        ),
    ]
