# Generated by Django 4.1.3 on 2022-11-11 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNumber', models.CharField(max_length=50)),
                ('expirationDate', models.DateField()),
                ('cvv', models.CharField(max_length=5)),
                ('postcode', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('time', models.DateTimeField()),
                ('user_id', models.IntegerField()),
                ('cardInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.cardinfo')),
            ],
        ),
    ]
