# Generated by Django 4.1.3 on 2022-11-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinfo',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
