# Generated by Django 4.1.3 on 2022-11-14 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0002_cardinfo_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardinfo',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='cardInfo',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='user_id',
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='cardNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='cvv',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='expirationDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='postcode',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
