# Generated by Django 4.1.3 on 2022-11-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_futurepayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'verbose_name_plural': 'payment histories'},
        ),
    ]
