# Generated by Django 4.1.3 on 2022-11-14 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_alter_classes_startdate_alter_classes_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2022, 11, 14, 11, 5, 28, 20047)),
        ),
    ]
