# Generated by Django 4.1.3 on 2022-11-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_alter_classes_studio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name_plural': 'classes'},
        ),
    ]
