# Generated by Django 4.1.3 on 2022-11-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_alter_classes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='keyword',
            field=models.ManyToManyField(to='classes.keyword'),
        ),
    ]
