# Generated by Django 4.1.3 on 2022-11-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0014_alter_classes_keyword_alter_classes_studio'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recurrence',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
