# Generated by Django 4.1.3 on 2022-12-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0016_customenrolldrop_customschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customschedule',
            old_name='customtime',
            new_name='customclass',
        ),
        migrations.AddField(
            model_name='customschedule',
            name='customend',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customschedule',
            name='customstart',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
